services:
  geth:
    image: asen88/go-ethereum:latest
    container_name: devnet-node
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ~/ethereum:/root
    command: --http